# Generated by Django 4.0.1 on 2022-12-26 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedTimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=100)),
                ('Date', models.DateField()),
                ('Status', models.CharField(choices=[('OPEN', 'OPEN'), ('WORKING', 'WORKING'), ('DONE', 'DONE'), ('OVERDUE', 'OVERDUE')], default='OPEN', max_length=20)),
                ('Tag', models.ManyToManyField(to='mainApp.TagList')),
            ],
        ),
    ]
