# Generated by Django 4.1.1 on 2022-11-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_todo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Tag',
        ),
    ]
