# Generated by Django 4.1.1 on 2022-11-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_todo_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Tag',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
