# Generated by Django 4.1.1 on 2022-11-21 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_todo_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='CreatedTimestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 21, 26, 45, 44099)),
        ),
    ]
