# Generated by Django 4.1.1 on 2022-11-21 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_todo_createdtimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='CreatedTimestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
