# Generated by Django 4.1.1 on 2022-11-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_todo_createdtimestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Status',
        ),
    ]
