# Generated by Django 4.1.1 on 2022-11-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_remove_todo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='CreatedTimestamp',
        ),
        migrations.AddField(
            model_name='todo',
            name='Status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('WORKING', 'WORKING'), ('DONE', 'DONE'), ('OVERDUE', 'OVERDUE')], default='OPEN', max_length=20),
        ),
    ]
