# Generated by Django 4.1.1 on 2022-11-21 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_remove_todo_createdtimestamp_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='CreatedTimestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
