# Generated by Django 4.1.1 on 2022-11-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_todo_createdtimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Tag2',
            field=models.SlugField(default='-', max_length=100, unique=True),
        ),
    ]
