# Generated by Django 3.1.7 on 2022-11-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_todo_tag2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Tag2',
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
