# Generated by Django 4.0.1 on 2022-11-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_taglist_delete_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Tag',
        ),
    ]
