# Generated by Django 4.0.1 on 2022-11-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_alter_todo_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Tag',
        ),
    ]
