# Generated by Django 4.0.1 on 2022-11-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_todo_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagList',
        ),
    ]
